DROP TABLE IF EXISTS attempt CASCADE;
CREATE TABLE attempt (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  quiz_id INTEGER NOT NULL REFERENCES quiz(id) ON DELETE CASCADE,
  score INTEGER NOT NULL,
  attempted_at TIMESTAMP NOT NULL DEFAULT NOW(),
  sharable_url TEXT UNIQUE
);
