DROP TABLE IF EXISTS answer CASCADE;
CREATE TABLE answer (
  id SERIAL PRIMARY KEY NOT NULL,
  attempt_id INTEGER NOT NULL REFERENCES attempt(id) ON DELETE CASCADE,
  question_id INTEGER NOT NULL REFERENCES question(id) ON DELETE CASCADE,
  selected_answer BOOLEAN NOT NULL
);
