DROP TABLE IF EXISTS answer CASCADE;
CREATE TABLE answers (
  id SERIAL PRIMARY KEY NOT NULL,
  attempt_id INTEGER NOT NULL REFERENCES attempts(id) ON DELETE CASCADE,
  question_id INTEGER NOT NULL REFERENCES questions(id) ON DELETE CASCADE,
  selected_answer BOOLEAN NOT NULL
);
